### ISSUE TITLE
pip installation schlägt fehl

### ISSUE THREAD

**Issue by hupling** [it-at-m/dbt-oracle#4]
`pip install onnx` 
schlägt fehl. Das wird für KI benötigt

![grafik](https://github.com/it-at-m/dbt-oracle/assets/11695964/4b65d4c7-a842-41ed-b1cb-9c5ea3ae91d3)

@itgkarl

**Comment by itgkarl** [comment]
@hupling 
Das Image ist primär für die Nutzung von dbt in Verbindung mit Oracle-Datenbanken gedacht. onnx dazu zu installieren ist daher nicht der scope des Images und daher auch erst mal nicht getestet.

Aber hast du denn eine Idee woran der Fehler liegt? Wenn ein Fix keine großen Auswirkungen auf den primären scope das Image hat können wir das gerne gemeinsam entsprechend fixen. Da wäre ich aber auf deinen Input angewiesen.

Evt. versuch du deine Pipline noch mal mit der neusten Version. Ich habe gerade ein neues Image auf Basis von dbt:1.6.0 gebaut.
GibtHub hatte die eigentlich täglich laufenden nightly-builds auf Grund von Inaktivität leider seit 2 Monaten deaktiviert. Dein Versuch war also auf jeden Fall gegen nicht 100% aktuelle base-images.

**Comment by itgkarl** [comment]
@hupling
Ich habe einen internen test mit dem neuen Image gemacht.
Dabei war die Installation von onnx erfolgreich: `Successfully installed numpy-1.26.1 onnx-1.14.1`

Das müsstest du denke ich noch für deine Zwecke gegen das Artifactory umbauen. Aber generell scheint das Image onnx erst mal nicht im Weg zu stehen:

Hier mein interner Test: [go.muenchen.de/353](https://go.muenchen.de/353)

**Comment by hupling** [comment]
danke
